spring:
  application:
    name: double-eureka

---
spring:
  config:
    activate:
      on-profile: peer1
server:
  port: 1111
eureka:
  instance:
    hostname: peer1
    prefer-ip-address: false
  server:
    enableself-preservation: false
  client:
    register-with-eureka: false
#    serviceUrl:
#      defaultZone: http://peer2:1112/eureka/

---
#spring:
#  config:
#    activate:
#      on-profile: peer2
#server:
#  port: 1112
#eureka:
#  instance:
#    hostname: peer2
#    prefer-ip-address: false
#  server:
#    enableself-preservation: false
#  client:
#    serviceUrl:
#      defaultZone: http://peer1:1111/eureka/
